import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import ThemeProvider from "@/context/ThemeProvider";

const Inter = localFont({
  src: "../public/fonts/interVF.ttf",
  variable: "--font-inter",
  weight: "100 to 900",
});
const SpaceGrotesk = localFont({
  src: "../public/fonts/SpaceGroteskVF.ttf",
  variable: "--font-space-grotesk",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${Inter.className} ${SpaceGrotesk.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
